micronaut:
  application:
    name: salesscore
netty:
  default:
    allocator:
      max-order: 3


mongodb:
  uri: mongodb://teixeira:teixeira@localhost:27017/teixeira?authSource=admin
  options:
    maxConnectionIdleTime: 10000
    readConcern: majority
  cluster:
    maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
jpa:
  default:
    packages-to-scan:
      - 'dev.gustavoteixeira.adapter.secondary.db'

logger:
  levels:
    org:
      mongodb:
        driver: DEBUG